In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [4]:
for row in a:
    for cell in row:
        print(cell) 

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for row in a.flat:
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [7]:
print(a)
for row in np.nditer(a,order="c"):
    print(row)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
print(a)
for row in np.nditer(a,order="F"):
    print(row)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
3
6
9
1
4
7
10
2
5
8
11


In [11]:
print(a)
for row in np.nditer(a,order="F", flags=['external_loop']):
    print(row)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 3 6 9]
[ 1  4  7 10]
[ 2  5  8 11]


In [17]:
print(a)
for x in np.nditer(a,order="F", op_flags=['readwrite']):
    x[...]=x*x

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


In [23]:
b = np.arange(12).reshape(4,3)

In [24]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
for s, t in np.nditer([a,b]):
    print(s, t)

0 0
1 1
16 2
81 3
256 4
625 5
1296 6
2401 7
4096 8
6561 9
10000 10
14641 11
