# NumPy Basic Operations

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
print(arr[0]) # Should return 1
print(arr[1]) # 2
print(arr[2]) # 3
print(arr[3])
print(arr[4])
print(arr[5])
print(arr[6])
print(arr[0]+arr[2]) # Should return 4
print(arr[0]+arr[-1]) # 10

1
2
3
4
5
6
7
4
10


# 2 Dimention

In [7]:
a1 = np.array([
    [1,2,3],
    [4,5,6]
])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(a1.ndim)

2


In [14]:
print(type(a1))
print(a1.dtype)

<class 'numpy.ndarray'>
int32


In [12]:
a2 = np.array([
    [1,2,3],
    [4,5,6]
],dtype = np.float64)
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
print(type(a2))
print(a2.dtype)

<class 'numpy.ndarray'>
float64


In [17]:
print(a1.size)
print(a2.size)

6
6


In [18]:
print(a1.shape)
print(a2.shape)

(2, 3)
(2, 3)


# Complex dtype

In [19]:
a3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype = np.complex64)

In [20]:
a3

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]], dtype=complex64)

In [21]:
print(a3)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [22]:
print(a3.size)
print(a3.shape)
print(type(a3))

9
(3, 3)
<class 'numpy.ndarray'>


In [24]:
print(a3[0])
print(a3[1])
print(a3[2])

[1.+0.j 2.+0.j 3.+0.j]
[4.+0.j 5.+0.j 6.+0.j]
[7.+0.j 8.+0.j 9.+0.j]


In [27]:
print(a3[0])
print(a3[1])
print(a3[2])
print(a3[0]+a3[1]+a3[2])

[1.+0.j 2.+0.j 3.+0.j]
[4.+0.j 5.+0.j 6.+0.j]
[7.+0.j 8.+0.j 9.+0.j]
[12.+0.j 15.+0.j 18.+0.j]


# Zero metrices

In [31]:
zero_metrix = np.zeros((3,4))

In [32]:
print(zero_metrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
print(zero_metrix.shape)
print(zero_metrix.size)
print(zero_metrix.dtype)

(3, 4)
12
float64


In [37]:
b = np.ones((5,5), dtype= np.float64)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
print(b.all)

<built-in method all of numpy.ndarray object at 0x048F6800>


In [38]:
print(b.size)
print(b.shape)
print(b.dtype)

25
(5, 5)
float64


# Range

In [39]:
l = range(10)

In [41]:
l

range(0, 10)

In [42]:
l[0]

0

In [44]:
print(l[4])
print(l[5])
print(l[2])

4
5
2


In [48]:
li = np.arange(10)

In [49]:
print(li)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
print(li[0])

0


In [52]:
print(li[0])
print(li[2])
print(li[4])

0
2
4


In [54]:
lis = np.arange(1,1000,5)
print(lis)

[  1   6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
  91  96 101 106 111 116 121 126 131 136 141 146 151 156 161 166 171 176
 181 186 191 196 201 206 211 216 221 226 231 236 241 246 251 256 261 266
 271 276 281 286 291 296 301 306 311 316 321 326 331 336 341 346 351 356
 361 366 371 376 381 386 391 396 401 406 411 416 421 426 431 436 441 446
 451 456 461 466 471 476 481 486 491 496 501 506 511 516 521 526 531 536
 541 546 551 556 561 566 571 576 581 586 591 596 601 606 611 616 621 626
 631 636 641 646 651 656 661 666 671 676 681 686 691 696 701 706 711 716
 721 726 731 736 741 746 751 756 761 766 771 776 781 786 791 796 801 806
 811 816 821 826 831 836 841 846 851 856 861 866 871 876 881 886 891 896
 901 906 911 916 921 926 931 936 941 946 951 956 961 966 971 976 981 986
 991 996]


In [56]:
print(lis[199])

996


In [57]:
print(lis.size)

200


In [58]:
print(lis.shape)

(200,)


In [62]:
print(a1.min())
print(a1.max())
print(a1.sort())

1
6
None


In [63]:
print(a2.min())
print(a2.max())
print(a2.sort())

1.0
6.0
None


In [64]:
print(a3.min())
print(a3.max())
print(a3.sort())

(1+0j)
(9+0j)
None


In [66]:
print(a1.sum())
print(a2.sum())
print(a3.sum())

21
21.0
(45+0j)


In [68]:
print(a1.sum(axis = 0)) # Column wise
print(a2.sum(axis = 0)) # Column wise
print(a3.sum(axis = 0)) # Column wise

[5 7 9]
[5. 7. 9.]
[12.+0.j 15.+0.j 18.+0.j]


In [72]:
print(a1.sum(axis = 1)) # Row wise
print(a2.sum(axis = 1)) # Row wise
print(a3.sum(axis = 1)) # Row wise

[ 6 15]
[ 6. 15.]
[ 6.+0.j 15.+0.j 24.+0.j]
