In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[1])
print(arr[3])
print(arr[5])
print(arr[3])

1
2
4
6
4


In [4]:
print(arr[-1])
print(arr[-3])
print(arr[-5])

9
7
5


In [5]:
arr3D = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,4]
], dtype = np.int64)

In [6]:
print(arr3D[2][0])

6


In [7]:
print(arr3D[0][0])

1


In [8]:
print(arr3D[-1][-1])

4


In [9]:
print(arr3D[1,2])

6


In [10]:
print(arr3D[1,1])

5


In [13]:
print(arr3D)
print(arr3D[0,0])

[[1 2 3]
 [4 5 6]
 [6 7 4]]
1


In [14]:
print(arr3D[0:2,1:2])

[[2]
 [5]]


In [15]:
for row in arr3D:
    print(row)

[1 2 3]
[4 5 6]
[6 7 4]


In [16]:
for row in arr3D.flat:
    print(row)

1
2
3
4
5
6
6
7
4


In [21]:
arr3by2 = np.arange(6).reshape(3,2)
print(arr3by2)

[[0 1]
 [2 3]
 [4 5]]


In [22]:
print(arr3by2[0])

[0 1]


In [23]:
print(arr3by2[0,0])

0


In [25]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,0]
])
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,0]
]) 

In [26]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [27]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0, 6, 7, 8, 9, 0]])

In [28]:
arr1 = np.arange(30).reshape(2,15)
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [30]:
arr2 = np.hsplit(arr1,3)
print(arr2)

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [33]:
print(arr2[0])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]


In [34]:
print(arr2[1])

[[ 5  6  7  8  9]
 [20 21 22 23 24]]


In [36]:
print(arr2[2])

[[10 11 12 13 14]
 [25 26 27 28 29]]


In [37]:
result = np.vsplit(arr1,2)

In [38]:
print(result)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [39]:
print(result[0])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


In [40]:
print(result[1])

[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [41]:
ab = np.arange(12).reshape(3,4)

In [42]:
print(ab)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
boolean = ab > 5
print(boolean)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [45]:
print(ab[boolean])

[ 6  7  8  9 10 11]


In [47]:
print(ab[boolean]==5)

[False False False False False False]


In [48]:
print(ab[boolean]==9)

[False False False  True False False]
